name: m3u
on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"
  push:
    branches:
      - master
      - dev
jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          path: src
      - name: Checkout dist
        uses: actions/checkout@v4
        with:
          ref: dist
          path: dist
      - name: gen
        id: gen
        env:
          EXPORT_RAW: false
          EXPORT_JSON: false
        run: |
          cd src
          # 安装依赖
          pip install -r requirements.txt
          # 运行脚本生成文件，确保生成文件在 src/dist 目录下
          DEBUG=1 python iptv.py
          # 创建 dist 目录（如果不存在）
          mkdir -p ../dist
          # 复制生成的文件到 dist 目录
          cp -r src/dist/* ../dist/
          echo "gen_time=$(date '+%Y-%m-%d %H:%M:%S %z')" >>$GITHUB_OUTPUT
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./dist
          commit_message: update ${{ steps.gen.outputs.gen_time }}
          add_options: '-A'
          push_options: '--force'    
